server:
  port: 8888

spring:
  security:
    user:
      name: root
      password: monCode

  cloud:
    config:
      server:
        git:
          uri: https://github.com/GREGUSTIN/ExoRabbitConfig
          default-label: main
          clone-on-start: true





